# Default configuration for Vulnera Rust

[server]
host = "0.0.0.0"
port = 3000

[cache]
directory = ".vulnera_cache"
ttl_hours = 24
strategy = "FileOnly"

# Redis configuration (optional)
# [cache.redis]
# url = "redis://localhost:6379"
# pool_size = 10
# connection_timeout_seconds = 5
# command_timeout_seconds = 3
# retry_attempts = 3
# key_prefix = "vulnera:"
# enable_compression = true
# max_key_length = 250

[apis.osv]
base_url = "https://api.osv.dev/v1"
timeout_seconds = 30

[apis.nvd]
base_url = "https://services.nvd.nist.gov/rest/json"
timeout_seconds = 30
rate_limit_per_30s = 5  # Without API key, 50 with API key

[apis.ghsa]
graphql_url = "https://api.github.com/graphql"
timeout_seconds = 30

[logging]
level = "info"
format = "json"